In [1]:
# Import numpy library
import numpy as np

# Take item weights as input from the 

In [8]:
weights = eval(input("Enter:"))
item_weight = np.array(weights)
heaviest_item = np.max(item_weight)
lightest=np.min(item_weight)
print(heaviest_item)
print(lightest)



30
5


In [10]:
# Import numpy library
import numpy as np

# Take nested list which contains stock level data as input
stock_levels = eval(input())

stock_arr = np.array(stock_levels)
average_val=np.mean(stock_arr)
print(average_val)

14.6


In [13]:
# Import numpy library
import numpy as np

# Take user input for dimensions of the 2D array
n = int(input())  # number of rows
m = int(input())  # number of columns
arr_2d=np.arange(n*m).reshape(n,m)
print(arr_2d)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
