In [3]:
import numpy as np


In [72]:
myarr=np.array([20,49,32,223,4])

myarr
myarr.shape

(5,)

In [74]:
myarr[0]

np.int64(20)

In [6]:
myar2 = np.array([[20, 49, 32, 223, 4]],np.int32)

In [7]:
myar2[0,2]

np.int32(32)

In [8]:
myar2.shape

(1, 5)

In [9]:
myar2.dtype

dtype('int32')

In [10]:
myar2[0,2]=34

In [11]:
myar2

array([[ 20,  49,  34, 223,   4]], dtype=int32)

In [12]:
#array creation

In [76]:
listarrays = np.array([[23, 33, 53], [2, 4, 5], [23, 66, 32]])
listarrays

array([[23, 33, 53],
       [ 2,  4,  5],
       [23, 66, 32]])

In [14]:
listarrays.dtype

dtype('int64')

In [15]:
listarrays.shape

(3, 3)

In [16]:
listarrays.size


9

In [17]:
zeros=np.zeros((2,5))

In [18]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
rng=np.arange(12)

In [20]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [78]:
linespace=np.linspace(1,4,6)
linespace

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [22]:
linespace

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [23]:
emp=np.empty((4,6))

In [24]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.29061074e-306, 1.89146896e-307, 7.56571288e-307],
       [4.00544531e-307, 1.11261095e-306, 3.56043054e-307,
        1.37961641e-306, 2.22518251e-306, 1.33511969e-306],
       [6.23037996e-307, 9.34609790e-307, 8.45593934e-307,
        9.34600963e-307, 1.86921143e-306, 6.23061763e-307],
       [6.23053954e-307, 1.60220800e-306, 9.34609111e-307,
        1.69120824e-306, 1.42419530e-306, 2.22522596e-306]])

In [25]:
emplike=np.empty_like(linespace)

In [26]:
emplike

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [79]:
ide=np.identity(8)
ide

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [29]:
ide.shape

(8, 8)

In [30]:
arr=np.arange(36)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [32]:
arr=arr.reshape(3,12)

In [33]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [34]:
arr=arr.ravel()

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [36]:
x=[[2,53,6],[2,6,8],[23,5,66]]


In [37]:
arr=np.array(x)

In [38]:
arr

array([[ 2, 53,  6],
       [ 2,  6,  8],
       [23,  5, 66]])

In [39]:
arr.sum(axis=0)

array([27, 64, 80])

In [40]:
arr.sum(axis=1)

array([61, 16, 94])

In [41]:
arr.T

array([[ 2,  2, 23],
       [53,  6,  5],
       [ 6,  8, 66]])

In [80]:
ar=arr.flat
arr

array([[ 2, 53,  6],
       [ 2,  6,  8],
       [23,  5, 66]])

In [43]:
for item in ar:
    print(item)

2
53
6
2
6
8
23
5
66


In [44]:
arr.ndim

2

In [45]:
arr.size

9

In [46]:
arr.nbytes

72

In [81]:
one=np.array([23,4,5,22,5,33,76])
one


array([23,  4,  5, 22,  5, 33, 76])

In [48]:
one.size

7

In [49]:
one.argmax()

np.int64(6)

In [50]:
one.argmin()

np.int64(1)

In [51]:
one.argsort()

array([1, 2, 4, 3, 0, 5, 6])

In [52]:
arr.argmax(axis=0)

array([2, 0, 2])

In [53]:
arr.argmin(axis=1)

array([0, 0, 1])

In [54]:
arr.argsort(axis=0)

array([[0, 2, 0],
       [1, 1, 1],
       [2, 0, 2]])

In [55]:
arr.argsort(axis=1)

array([[0, 2, 1],
       [0, 1, 2],
       [1, 0, 2]])

In [56]:
arr.ravel()

array([ 2, 53,  6,  2,  6,  8, 23,  5, 66])

In [57]:
arr.reshape((9,1))

array([[ 2],
       [53],
       [ 6],
       [ 2],
       [ 6],
       [ 8],
       [23],
       [ 5],
       [66]])

In [58]:
ar3=np.array([[2,4,5],[2,5,33],[2,45,32]])

In [59]:
arr+ar3

array([[ 4, 57, 11],
       [ 4, 11, 41],
       [25, 50, 98]])

In [60]:
arr*ar3

array([[   4,  212,   30],
       [   4,   30,  264],
       [  46,  225, 2112]])

In [61]:
np.sqrt(ar3)

array([[1.41421356, 2.        , 2.23606798],
       [1.41421356, 2.23606798, 5.74456265],
       [1.41421356, 6.70820393, 5.65685425]])

In [62]:
arr.max()

np.int64(66)

In [63]:
arr.min()

np.int64(2)

In [64]:
arr.sum()

np.int64(171)

In [65]:
np.where(arr>34)

(array([0, 2]), array([1, 2]))

In [84]:
np.count_nonzero(ar3)


8

In [67]:
np.nonzero(ar3)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [68]:
ar3[1,1]=0


In [85]:
np.nonzero(ar3)

(array([0, 0, 0, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 2, 0, 1, 2]))