In [2]:
import numpy as np
rng = np.random.default_rng()
A = rng.normal(size=(4, 4))
b = rng.normal(size=4)

x_sol = np.linalg.solve(A, b)  # Ax=b
eigvals, eigvecs = np.linalg.eig(A)
U, S, VT = np.linalg.svd(A)  # SVD
Q, R = np.linalg.qr(A)  # QR
normA = np.linalg.norm(A, ord=2)  # spectral norm

x_sol, eigvals, S, normA, (Q.shape, R.shape)

(array([-2.16800963,  1.05959955,  0.20477335, -0.42279626]),
 array([ 0.71996276+1.6580347j,  0.71996276-1.6580347j,
        -0.88847067+0.j       ,  0.50094292+0.j       ]),
 array([3.23373689, 1.98078339, 0.67850178, 0.3346142 ]),
 np.float64(3.233736889627048),
 ((4, 4), (4, 4)))

In [4]:
from numpy.lib.stride_tricks import sliding_window_view

x = np.arange(1, 11)
W = sliding_window_view(x, window_shape=3)  # shape (8,3)
rolling_mean = W.mean(axis=1)
W, rolling_mean

(array([[ 1,  2,  3],
        [ 2,  3,  4],
        [ 3,  4,  5],
        [ 4,  5,  6],
        [ 5,  6,  7],
        [ 6,  7,  8],
        [ 7,  8,  9],
        [ 8,  9, 10]]),
 array([2., 3., 4., 5., 6., 7., 8., 9.]))

In [3]:
rng = np.random.default_rng(7)
normals = rng.normal(size=(2, 3))
ints = rng.integers(0, 10, size=5)
choice = rng.choice(np.arange(10), size=4, replace=False)
perm = rng.permutation(np.arange(6))
normals, ints, choice, perm

(array([[ 0.00123015,  0.29874554, -0.27413786],
        [-0.89059184, -0.45467079, -0.99164655]]),
 array([9, 0, 4, 8, 1]),
 array([4, 5, 8, 0]),
 array([5, 3, 4, 1, 2, 0]))

In [5]:
dates = np.array(["2025-01-01", "2025-01-03", "2025-02-01"], dtype="datetime64[D]")
deltas = np.diff(dates)
add7 = dates + np.timedelta64(7, "D")
dates, deltas, add7

(array(['2025-01-01', '2025-01-03', '2025-02-01'], dtype='datetime64[D]'),
 array([ 2, 29], dtype='timedelta64[D]'),
 array(['2025-01-08', '2025-01-10', '2025-02-08'], dtype='datetime64[D]'))