In [2]:
import numpy as np


In [3]:
rng = np.random.default_rng(42)


In [4]:
np.__version__

'2.2.6'

In [5]:
a=np.array([1,2,3],dtype=np.int64)
a

array([1, 2, 3])

In [6]:
b = np.array([[1, 2, 3],[4., 5., 6.]], dtype=np.int64)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
ar=np.arange(0,10,2)
ar

array([0, 2, 4, 6, 8])

In [8]:
lin=np.linspace(0,4,8)
lin

array([0.        , 0.57142857, 1.14285714, 1.71428571, 2.28571429,
       2.85714286, 3.42857143, 4.        ])

In [9]:
log=np.logspace(1,3,num=4)
log

array([  10.        ,   46.41588834,  215.443469  , 1000.        ])

In [10]:
nz=np.zeros((2,3))
nz

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
o= np.full((2, 3),fill_value=7)
o

array([[7, 7, 7],
       [7, 7, 7]])

In [12]:
i=np.eye(4)
i

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
D = np.diag([10, 20, 30])
D

array([[10,  0,  0],
       [ 0, 20,  0],
       [ 0,  0, 30]])

In [14]:
x = rng.normal(size=(3, 4))
x

array([[ 0.30471708, -1.03998411,  0.7504512 ,  0.94056472],
       [-1.95103519, -1.30217951,  0.1278404 , -0.31624259],
       [-0.01680116, -0.85304393,  0.87939797,  0.77779194]])

In [15]:
shape = x.shape
shape

(3, 4)

In [16]:
ndim = x.ndim
ndim

2

In [17]:
dtype = x.dtype
dtype

dtype('float64')

In [18]:
size = x.size
size

12

In [19]:
itemsize = x.itemsize
itemsize

8

In [20]:
nbytes = x.nbytes
nbytes

96

In [21]:
strides = x.strides
strides

(32, 8)

In [22]:
d = np.array([2,4,5,9],dtype=np.int32)
d.dtype

dtype('int32')

In [23]:
d32 = d.astype(np.int32, copy=True)
d32.dtype



dtype('int32')

In [24]:
f64=d32.astype(np.float64,copy=True)
d32.dtype

dtype('int32')

In [25]:
s = np.arange(10)
view=s[::2]
view[...] = -1
copy=s[1:6].copy()
s ,view,copy

(array([-1,  1, -1,  3, -1,  5, -1,  7, -1,  9]),
 array([-1, -1, -1, -1, -1]),
 array([ 1, -1,  3, -1,  5]))

In [26]:
# 2D Indexing Helpers
m = np.arange(1, 13).reshape(3, 4)
rows=m[0]
cols=m[:,-1]
rows01_cols13 = M[np.ix_([0, 1], [1, 3])]
m, rows, cols, rows01_cols13

NameError: name 'M' is not defined

In [ ]:
v = np.arange(0, 21)
mask = (v % 3==0)
selected = v[mask]
where_demo=np.where(v%2==0,v,"odd")
v,mask,selected,where_demo

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20]),
 array([ True, False, False,  True, False, False,  True, False, False,
         True, False, False,  True, False, False,  True, False, False,
         True, False, False]),
 array([ 0,  3,  6,  9, 12, 15, 18]),
 array(['0', 'odd', '2', 'odd', '4', 'odd', '6', 'odd', '8', 'odd', '10',
        'odd', '12', 'odd', '14', 'odd', '16', 'odd', '18', 'odd', '20'],
       dtype='<U21'))

In [ ]:
# 7) Reshape & Axis Moves
r=np.arange(12)
re=r.reshape(3,4)
ravel_veiw=re.ravel()
flattem=re.flatten()
T = re.T
swapped=np.swapaxes(re.reshape(2,3,2),0,1)
moved = np.moveaxis(np.zeros((2, 3, 4)), 0, -1).shape

r,re,ravel_veiw,flattem,T,swapped,moved

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]]),
 array([[[ 0,  1],
         [ 6,  7]],
 
        [[ 2,  3],
         [ 8,  9]],
 
        [[ 4,  5],
         [10, 11]]]),
 (3, 4, 2))

In [ ]:
A = np.arange(6).reshape(2, 3)
B = A + 10
vert_stack=np.stack([A,B])
hstacked = np.hstack([A, B])                                                                        





A,B,vert_stack,hstacked

(array([[0, 1, 2],
        [3, 4, 5]]),
 array([[10, 11, 12],
        [13, 14, 15]]),
 array([[[ 0,  1,  2],
         [ 3,  4,  5]],
 
        [[10, 11, 12],
         [13, 14, 15]]]),
 array([[ 0,  1,  2, 10, 11, 12],
        [ 3,  4,  5, 13, 14, 15]]))

In [27]:
a = np.array([1.0, 2.0, np.nan, 4.0])
basic = (a.sum(), a.mean(), a.min(), a.max(), a.std(), a.var())
nan_safe = (np.nansum(a), np.nanmean(a), np.nanmin(a), np.nanmax(a))
basic, nan_safe

((np.float64(nan),
  np.float64(nan),
  np.float64(nan),
  np.float64(nan),
  np.float64(nan),
  np.float64(nan)),
 (np.float64(7.0),
  np.float64(2.3333333333333335),
  np.float64(1.0),
  np.float64(4.0)))

In [29]:
t = rng.integers(0, 100, size=12)
sorted_t = np.sort(t)
idx = np.argsort(t)  # positions
top3_vals = np.partition(t, -3)[-3:]  # unordered top3
top3_idx = np.argpartition(t, -3)[-3:]
(sorted_t, idx, top3_vals, top3_idx, t[top3_idx])

(array([ 6,  9, 22, 40, 44, 45, 54, 55, 64, 78, 82, 88]),
 array([11,  8,  7,  2,  5,  6,  4,  9,  1,  0,  3, 10]),
 array([78, 82, 88]),
 array([ 0,  3, 10]),
 array([78, 82, 88]))

In [ ]:
last = np.array(["e", "d", "a", "b", "c"])
first = np.array([2, 2, 1, 1, 1])
order = np.lexsort((last, first))  # primary=first, secondary=last
first[order], last[order]

In [2]:
import numpy as np
u = np.array([1, 2, 2, 3, 4, 4, 5])
uniq, counts = np.unique(u, return_counts=True)
inter = np.intersect1d([1, 2, 3], [2, 3, 4])
union = np.union1d([1, 2, 3], [2, 3, 4])
diff = np.setdiff1d([1, 2, 3, 4], [2, 4])
isin = np.isin([1, 4, 6], [1, 2, 3, 4, 5])
(uniq, counts), inter, union, diff, isin

((array([1, 2, 3, 4, 5]), array([1, 2, 1, 2, 1])),
 array([2, 3]),
 array([1, 2, 3, 4]),
 array([1, 3]),
 array([ True,  True, False]))

In [4]:
import numpy as np
A = rng.normal(size=(4, 4))
b = rng.normal(size=4)

x_sol = np.linalg.solve(A, b)  # Ax=b
eigvals, eigvecs = np.linalg.eig(A)
U, S, VT = np.linalg.svd(A)  # SVD
Q, R = np.linalg.qr(A)  # QR
normA = np.linalg.norm(A, ord=2)  # spectral norm

x_sol, eigvals, S, normA, (Q.shape, R.shape)

NameError: name 'rng' is not defined